name: ocetrac-dask
channels:
  - conda-forge
dependencies:
  # Required for full project functionality 
  - pytest
  # Examples 
  - jupyter
  - jupyterlab
  - xarray
  - scipy
  - dask
  - scikit-image
  - dask_image
